### DEFECTS Projects

In [9]:
from warnings import filterwarnings
filterwarnings('ignore')

### READING DATASETS

In [10]:
import pandas as pd

In [11]:
df=pd.read_csv('train.csv')
df.head()

,id,loc,v(g),ev(g),iv(g),n,v,l,d,i,...,lOCode,lOComment,lOBlank,locCodeAndComment,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount,defects
0,0,22.0,3.0,1.0,2.0,60.0,278.63,0.06,19.56,14.25,...,17,1,1,0,16.0,9.0,38.0,22.0,5.0,False
1,1,14.0,2.0,1.0,2.0,32.0,151.27,0.14,7.00,21.11,...,11,0,1,0,11.0,11.0,18.0,14.0,3.0,False
2,2,11.0,2.0,1.0,2.0,45.0,197.65,0.11,8.05,22.76,...,8,0,1,0,12.0,11.0,28.0,17.0,3.0,False
3,3,8.0,1.0,1.0,1.0,23.0,94.01,0.19,5.25,17.86,...,4,0,2,0,8.0,6.0,16.0,7.0,1.0,True
4,4,11.0,2.0,1.0,2.0,17.0,60.94,0.18,5.63,12.44,...,7,0,2,0,7.0,6.0,10.0,10.0,3.0,False

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101763 entries, 0 to 101762
Data columns (total 23 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 101763 non-null  int64
 1   loc                101763 non-null  float64
 2   v(g)               101763 non-null  float64
 3   ev(g)              101763 non-null  float64
 4   iv(g)              101763 non-null  float64
 5   n                  101763 non-null  float64
 6   v                  101763 non-null  float64
 7   l                  101763 non-null  float64
 8   d                  101763 non-null  float64
 9   i                  101763 non-null  float64
 10  e                  101763 non-null  float64
 11  b                  101763 non-null  float64
 12  t                  101763 non-null  float64
 13  lOCode             101763 non-null  int64
 14  lOComment          101763 non-null  int64
 15  lOBlank            101763 non-null  int64
 16  locCodeAndComment  101763 non-null  int64
 17  uniq_Op            101763 non-null  float64
 18  uniq_Opnd          101763 non-null  float64
 19  total_Op           101763 non-null  float64
 20  total_Opnd         101763 non-null  float64
 21  branchCount        101763 non-null  float64
 22  defects            101763 non-null  bool
dtypes: bool(1), float64(17), int64(5)
memory usage: 17.2 MB

In [13]:
df.isna().sum()

id                   0
loc                  0
v(g)                 0
ev(g)                0
iv(g)                0
n                    0
v                    0
l                    0
d                    0
i                    0
e                    0
b                    0
t                    0
lOCode               0
lOComment            0
lOBlank              0
locCodeAndComment    0
uniq_Op              0
uniq_Opnd            0
total_Op             0
total_Opnd           0
branchCount          0
defects              0
dtype: int64

In [14]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
id,101763.0,50881.000000,29376.592059,0.0,25440.50,50881.00,76321.50,101762.00
loc,101763.0,37.347160,54.600401,1.0,13.00,22.00,42.00,3442.00
v(g),101763.0,5.492684,7.900855,1.0,2.00,3.00,6.00,404.00
ev(g),101763.0,2.845022,4.631262,1.0,1.00,1.00,3.00,165.00
iv(g),101763.0,3.498826,5.534541,1.0,1.00,2.00,4.00,402.00
n,101763.0,96.655995,171.147191,0.0,25.00,51.00,111.00,8441.00
v,101763.0,538.280956,1270.791601,0.0,97.67,232.79,560.25,80843.08
l,101763.0,0.111634,0.100096,0.0,0.05,0.09,0.15,1.00
d,101763.0,13.681881,14.121306,0.0,5.60,9.82,18.00,418.20
i,101763.0,27.573007,22.856742,0.0,15.56,23.36,34.34,569.78
e,101763.0,20853.589876,190571.405427,0.0,564.73,2256.23,10193.24,16846621.12
b,101763.0,0.179164,0.421844,0.0,0.03,0.08,0.19,26.95
t,101763.0,1141.357982,9862.795472,0.0,31.38,125.40,565.92,935923.39
lOCode,101763.0,22.802453,38.541010,0.0,7.00,14.00,26.00,2824.00
lOComment,101763.0,1.773945,5.902412,0.0,0.00,0.00,1.00,344.00
lOBlank,101763.0,3.979865,6.382358,0.0,1.00,2.00,5.00,219.00
locCodeAndComment,101763.0,0.196604,0.998906,0.0,0.00,0.00,0.00,43.00
uniq_Op,101763.0,11.896131,6.749549,0.0,8.00,11.00,16.00,410.00
uniq_Opnd,101763.0,15.596671,18.064261,0.0,7.00,12.00,20.00,1026.00
total_Op,101763.0,57.628116,104.537660,0.0,15.00,30.00,66.00,5420.00
total_Opnd,101763.0,39.249698,71.692309,0.0,10.00,20.00,45.00,3021.00
branchCount,101763.0,9.839549,14.412769,1.0,3.00,5.00,11.00,503.00

### SEPEARATING X AND Y

In [15]:
X = df.drop(columns=['id','defects'])
Y = df[['defects']]

In [22]:
from sklearn.preprocessing import OrdinalEncoder,LabelEncoder
le=LabelEncoder()
ord=OrdinalEncoder()

In [24]:
Y['defects']=le.fit_transform(Y['defects'])
Y.head()

   defects
0        0
1        0
2        0
3        1
4        0

In [25]:
X.head()

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,...,t,lOCode,lOComment,lOBlank,locCodeAndComment,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount
0,22.0,3.0,1.0,2.0,60.0,278.63,0.06,19.56,14.25,5448.79,...,302.71,17,1,1,0,16.0,9.0,38.0,22.0,5.0
1,14.0,2.0,1.0,2.0,32.0,151.27,0.14,7.00,21.11,936.71,...,52.04,11,0,1,0,11.0,11.0,18.0,14.0,3.0
2,11.0,2.0,1.0,2.0,45.0,197.65,0.11,8.05,22.76,1754.01,...,97.45,8,0,1,0,12.0,11.0,28.0,17.0,3.0
3,8.0,1.0,1.0,1.0,23.0,94.01,0.19,5.25,17.86,473.66,...,26.31,4,0,2,0,8.0,6.0,16.0,7.0,1.0
4,11.0,2.0,1.0,2.0,17.0,60.94,0.18,5.63,12.44,365.67,...,20.31,7,0,2,0,7.0,6.0,10.0,10.0,3.0

In [26]:
Y.head()

   defects
0        0
1        0
2        0
3        1
4        0

In [27]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

In [28]:
num_pipe=Pipeline(steps=[('impute',SimpleImputer(strategy='median')),
                         ('scaler',StandardScaler())])

In [29]:
x_pre=num_pipe.fit_transform(X)
x_pre[0:5]

array([[-0.28108282, -0.31549702, -0.39838633, -0.27081433, -0.21417924,
        -0.20432322, -0.515843  ,  0.41626091, -0.58289463, -0.08083519,
        -0.21136819, -0.08503189, -0.15055343, -0.13112422, -0.4668932 ,
        -0.19682008,  0.60802414, -0.3651798 , -0.18776212, -0.24060855,
        -0.33578367],
       [-0.42760261, -0.44206622, -0.39838633, -0.27081433, -0.37778191,
        -0.30454471,  0.28339468, -0.47317961, -0.2827629 , -0.10451189,
        -0.30619036, -0.11044773, -0.30623253, -0.30054732, -0.4668932 ,
        -0.19682008, -0.13276969, -0.2544634 , -0.37908167, -0.35219708,
        -0.47455019],
       [-0.48254753, -0.44206622, -0.39838633, -0.27081433, -0.30182353,
        -0.26804759, -0.01631945, -0.39882352, -0.21057378, -0.10022319,
        -0.25877927, -0.10584353, -0.38407207, -0.30054732, -0.4668932 ,
        -0.19682008,  0.01538907, -0.2544634 , -0.2834219 , -0.31035138,
        -0.47455019],
       [-0.53749246, -0.56863542, -0.39838633, -0.45149868, -0.43036848,
        -0.34960346,  0.78291824, -0.59710644, -0.42495359, -0.1069417 ,
        -0.35360144, -0.11305653, -0.48785814, -0.30054732, -0.31021053,
        -0.19682008, -0.57724599, -0.53125439, -0.39821363, -0.44983704,
        -0.61331671],
       [-0.48254753, -0.44206622, -0.39838633, -0.27081433, -0.4654262 ,
        -0.37562674,  0.68301353, -0.57019661, -0.66208391, -0.10750837,
        -0.37730698, -0.11366488, -0.41001859, -0.30054732, -0.31021053,
        -0.19682008, -0.72540476, -0.53125439, -0.45560949, -0.40799135,
        -0.47455019]])

In [30]:
cols= num_pipe.get_feature_names_out()
cols

array(['loc', 'v(g)', 'ev(g)', 'iv(g)', 'n', 'v', 'l', 'd', 'i', 'e', 'b',
       't', 'lOCode', 'lOComment', 'lOBlank', 'locCodeAndComment',
       'uniq_Op', 'uniq_Opnd', 'total_Op', 'total_Opnd', 'branchCount'],
      dtype=object)

In [31]:
X_pre=pd.DataFrame(x_pre,columns=cols)
X_pre

,loc,v(g),ev(g),iv(g),n,v,l,d,i,e,...,t,lOCode,lOComment,lOBlank,locCodeAndComment,uniq_Op,uniq_Opnd,total_Op,total_Opnd,branchCount
0,-0.281083,-0.315497,-0.398386,-0.270814,-0.214179,-0.204323,-0.515843,0.416261,-0.582895,-0.080835,...,-0.085032,-0.150553,-0.131124,-0.466893,-0.19682,0.608024,-0.365180,-0.187762,-0.240609,-0.335784
1,-0.427603,-0.442066,-0.398386,-0.270814,-0.377782,-0.304545,0.283395,-0.473180,-0.282763,-0.104512,...,-0.110448,-0.306233,-0.300547,-0.466893,-0.19682,-0.132770,-0.254463,-0.379082,-0.352197,-0.474550
2,-0.482548,-0.442066,-0.398386,-0.270814,-0.301824,-0.268048,-0.016319,-0.398824,-0.210574,-0.100223,...,-0.105844,-0.384072,-0.300547,-0.466893,-0.19682,0.015389,-0.254463,-0.283422,-0.310351,-0.474550
3,-0.537492,-0.568635,-0.398386,-0.451499,-0.430368,-0.349603,0.782918,-0.597106,-0.424954,-0.106942,...,-0.113057,-0.487858,-0.300547,-0.310211,-0.19682,-0.577246,-0.531254,-0.398214,-0.449837,-0.613317
4,-0.482548,-0.442066,-0.398386,-0.270814,-0.465426,-0.375627,0.683014,-0.570197,-0.662084,-0.107508,...,-0.113665,-0.410019,-0.300547,-0.310211,-0.19682,-0.725405,-0.531254,-0.455609,-0.407991,-0.474550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101758,-0.500863,-0.442066,-0.398386,-0.451499,-0.401154,-0.326807,0.383299,-0.501506,-0.391265,-0.105168,...,-0.111152,-0.410019,-0.300547,-0.466893,-0.19682,-0.132770,-0.420538,-0.398214,-0.380094,-0.474550
101759,-0.189508,-0.062359,0.249389,-0.451499,0.060440,0.017036,-0.515843,0.305789,0.288625,-0.050298,...,-0.052252,0.005126,-0.300547,-0.310211,-0.19682,0.904342,0.243760,0.089651,0.010466,-0.058251
101760,-0.207823,-0.568635,-0.398386,-0.451499,-0.079791,-0.140158,-0.715652,0.642162,-0.656834,-0.078501,...,-0.082525,-0.072714,-0.300547,0.003155,-0.19682,-0.280928,-0.420538,-0.063404,-0.156917,-0.613317
101761,-0.500863,-0.442066,-0.398386,-0.270814,-0.313509,-0.272683,0.383299,-0.511420,0.085620,-0.101377,...,-0.107084,-0.410019,-0.300547,-0.466893,-0.19682,-0.132770,-0.088389,-0.321686,-0.282454,-0.474550
101762,1.806824,1.583041,3.272338,-0.451499,1.164758,0.917770,-0.915462,2.205056,0.722197,0.294681,...,0.318073,2.054900,-0.131124,1.099933,-0.19682,1.496977,0.852701,0.998419,1.335579,1.745714